# Aplicacao
spring.application.name=task
server.port=8080

# DB
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
api.security.token.secret = senha-task-application
api.security.token.expiration = 2

# DEBUG (COMENTAR ANTES DE SUBIR!)
    #Spring Security
    #logging.level.org.springframework.security=DEBUG
