# Aplicacao
spring.application.name=task
server.port=8080

# DB
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
api.security.token.secret = senha-task-application
api.security.token.expiration = 2

# Seeder
app.seeder.enabled = true

# P6Spy
#decorator.datasource.p6spy.enable=true
#decorator.datasource.p6spy.logging=sysout
#decorator.datasource.p6spy.log-format=%(executionTime)ms | %(category) | connection %(connectionId) | %(sqlSingleLine)

# DEBUG (COMENTAR ANTES DE SUBIR!)
    #Spring Security
#    logging.level.org.springframework.security=DEBUG
